const theRoomQuotes = [
    "Hy babe, I got something for you!",
    "Anything for my princess!",
    "I would do anything for my girl",
    "Oh, hi Danny.",
    "Can I go upstairs too?",
    "Oh Johnny, it's beautiful!",
    "How much was it?",
    "This is so pretty, I can't wait for you to get it off of me.",
    "Danny, do you have something else to do?",
    "Danny, two is great, but three is a crowd.",
    "I don't love Johnny any more.",
    "Oh, hy doggy.",
    "You're my favorite customer!",
    "I just like to watch you guys.",
    "Keep the change.",
    "Anyway, how's your sex life?",
    "If a lot of people love each other, the world would be a better place.",
    "What a story Mark!",
    "You seem to be the expert, Mark!",
    "HA HA HA HA!",
    "I am so happy to have you in my life as my best friend and Lisa as my future life.",
    "Wow, you look so sexy Lisa!",
    "Did you like last night?",
    "The results of the test are back. I definitely have breast cancer!",
    "OK, let's go to the couch, and we will sit down. Now, what's happening with you?",
    "I don't love him anymore.",
    "Why don't you love him anymore, tell me?",
    "He's so boring.",
    "You said you loved him. He supports you, he provides for you, and you can't support yourself.",
    "You can't support yourself.",
    "He's a wonderful man, and he loves you very much. And his position is very secure.",
    "That's why he's so boring!",
    "Now, he bought you a car, he bought you a ring, clothes, whatever you wanted. Now you want to dump him? That's not right.",
    "You should marry Johnny, he would be good for you.",
    "Well of course I'm right, I know men. I wasn't born yesterday.",
    "I'm glad you're listending to your mother, no one else listens to me.",
    "Hey baby, how you're doing?",
    "She's a stupid bitch, she wants to control my life. I'm not gonna' put up with that. I'm gonna' do what I want to do, and that's it.",
    "I mean... the candles, the music... the sexy dress.. I mean, what's going on here?",
    "It's hot in here. Do you mind?",
    "I like you very much... lover boy.",
    "Johnny's my best friend!",
    "Forget about Johnny! This is between you and me.",
    "I need you to make love with me.",
    "Keep the change.",
    "Oh hy Johnny, I didn't know it was you.",
    "You're my favorite customer!",
    "Oh, hy doggy.",
    "I already ordered pizza!",
    "You look beautiful today. Can I kiss you?",
    "They betray me, they didn't keep their promise, they tricked me and I don't care any more.",
    "At least you have friends. I didn't get any calls today.",
    "You're right, the computer business is too competitive.",
    "You know what you need? You need a drink.",
    "If you love me, you'll drink this.",
    "Drink and let's have some fun.",
    "I'm tired, I'm wasted, I love you darling!",
    "You have nice legs, Lisa.",
    "A ha ha!",
    "Ow, that jerk Harold. He wants me to give him a share of my house.",
    "Fiveteen years ago, we agreed that house belongs to me. Now the value of the house is going up and he sees dollar signs.",
    "Everything goes wrong at once. No one wants to help me, and I'm dying.",
    "I'w got the results of the test back. I definitelly got breast canser.",
    "I heard Edward is talking about me. He is a hatefull man, I'm so glad I divorced him.",
    "Well at least you have a good man!",
    "Mom, he is not what you think he is.",
    "He didn't get his promotion.",
    "He didn't get his promotion. And he got drunk last nigh, and he hit me.",
    "Johnny is your financial security, you can't ignore this.",
    "Did you know, that chocolate is a symbol of love?",
    "Chocolate is the symbol of love!",
    "What are these characters doing here?",
    "Ohh... all that shopping wore me out!",
    "How many people come in and out of this appartment every day? This is worst than Grand Central Station!",
    "I just wanted to borrow some suggar. I also need a cup of flower and half a stick of butter.",
    "Please, don't hurt Johnny. Now, if you really don't love him, so be it. But don't hurt him.",
    "Chris R, I'w been looking for you.",
    "You have my money, right?",
    "What you mean it's comming Danny? Where's my money?",
    "Five minutes? You want five fucking minutes Danny?",
    "Stop ganging up on me!",
    "Where's my money Danny? Where's my fucking money Danny?! Give me my fucking money!",
    "What kind of drugs?",
    "Ow, that was not nothin!",
    "What kind of money?",
    "Calm down, he's going to jail!",
    "I bought some drugs off of him. Things got mixed up.",
    "What kind of drungs do you take!",
    "I just needed some money to pay off some stuff!",
    "It matters a great deal!",
    "You're not my fucking mother!",
    "You know that Johnny is like your father, and we're your friends, we're gonna' help you.",
    "I just saw you, what are you talking about?",
    "I just wanted to hear your sexy woice. I keep thinking about your strong arms around my body, it excites me so much.",
    "I don't understand you, why do you do things like this?",
    "You just don't care, do you?",
    "I do care!",
    "I did not hit her, it's not true. It's bullshit, I did not hit her. I did not. Oh, hy Mark.",
    "Well I'm just sitting up here thinking.",
    "I got a question for you. You think girls like to cheat like guys do?",
    "I don't have to worry about that, because Lisa is loyal to me.",
    "Yea man, you never know.",
    "People are very strange these days.",
    "Hahahaha. What a story Mark!",
    "Yea, you can say that again!",
    "I used to know a girl, she had a duzen guys. One of them found out, beat her up so hard she ended up in hospital on Guerrero Street!",
    "Yea, you can say that again!",
    "I'm so happy I have you as my best friend and I love Lisa so much.",
    "Well maybe you should have a girl Mark.",
    "You know, she wasn't any good in bed. She was beautiful, but we had too many arguments.",
    "That's too bad, my Lisa is great when I can get it.",
    "Oh man, I just can't figgure women out. Sometimes the're too smart, sometimes the're stupid... other times the're just evil.",
    "Oh man, I just can't figgure women out.",
    "It seems to me you're the expert Mark!",
    "Well, whatever.",
    "Girl trouble, I guess.",
    "Danny don't plan too much. It may not come out right.",
    "Let's toss the ball around.",
    "She's beautiful, she looks great in her red dress. I think I'm in love with her.",
    "I know she doesn't like me, becouse sometimes she's mean to me.",
    "Lisa loves you too. As a person, as a friend, as a human being.",
    "If a lot of people loved each other, a world would be a better place to live.",
    "Lisa's your future wife.",
    "No, because I trust you, and I trust Lisa.",
    "That's the idea.",
    "Thanks for paying my tuition.",
    "He didn't get his promotion.",
    "He got drunk last night and he hit me.",
    "Well, I don't want to marry him anymore.",
    "Johnny's OK, but I found someone else.",
    "Lisa! This isn't right. You're living with one guy and sleeping with another guy.",
    "I'm doing what I want to do.",
    "No guilt trips!",
    "It's between us women.",
    "It's girl talk.",
    "I'm your future husband.",
    "You sure about that? Maybe I'll change my mind.",
    "Women change their minds all the time.",
    "Why Lisa, why Lisa! Please, talk to me, please!",
    "You're scaring me.",
    "Why are you so histerical?",
    "You are tearing me apart Lisa!",
    "Do you understand life? Do you?",
    "You tramp.",
    "Don't worry about it. I still love you.",
    "I got a little bit of a tragedy on my hands.",
    "Half way down staris I realize I have misplaced... I have forgotten something. My underwear!",
    "That's life.",
    "I got to see Michelle in a little bit, to make out with her.",
    "I don't study like that.",
    "Are you OK!?",
    "Listen, if you need anything call me, any time.",
    "Let's go home Danny.",
    "All he could tell me is 'It's an awkward situation'.",
    "You don't want to talk about it? Then why did you bring it up in the first place?",
    "If you think I'm tired today, wait until you see me tomorow.",
    "I show them.",
    "I don't understand women. They never say what they mean, and they always play games.",
    "I don't think she's fateful to me. In fact, I'm sure she isn't.",
    "But you are psychologist.",
    "I can't confront her. I want to give her a second chance. After all, she's my future wife.",
    "You know what they say. Love is blind.",
    "Love is blind.",
    "Sometimes life gets complicated, the unexpected can happen. When it does you just have to deal with it.",
    "Women just confuse me.",
    "Peter you always play psychologist with us!",
    "We didn't make love in a while.",
    "You can work out everything as long as you talk abou it.",
    "People are people.",
    "You guys are too much.",
    "Chicken Peter, you just a little chicken.",
    "You remember the one with big tits, the blondy one?",
    "I didn't want to chase you off.",
    "What man, you want to put me on the clock?",
    "You know I don't smoke that stuff.",
    "Hey everybody, let's eat cake!",
    "You look baby face.",
    "Chip chip chip chip chip",
    "Anyway, how's your sex life?",
    "I'm so tired of girls games.",
    "Life's too short.",
    "How about something like cheese cake. It's realy goooood.",
    "Just one more time.",
    "You guys are too much.",
    "Tricky tricky.",
    "Suddenly my eyes are wide open and I see clearly. I want it all.",
    "If he can't give me everything I want, someone else will.",
    "You're sounding just like your mother.",
    "You're being so manipulative.",
    "You have to take as much as you can. You have to live, live, live.",
    "Look, I don't want to talk about it.",
    "Doesn't everybod look out for number one. Don't I deserve the best?",
    "You expect to be happy? I haven't been happy ever since I married my first husband.",
    "All men are assholes. Men and women use and abuse each other all the time, there's nothing wrong with that.",
    "Marriage has nothing to do with love!",
    "I have him wrapped around my little finger.",
    "Don't throw your life away just because you dont love him.",
    "You're going to destroy Johnny, he's very sensitive!",
    "Leave your stupid comments in your pocket!",
    "There is no baby. I told him that to make it interesting. We're probably going to have a baby eventually anyway.",
    "I feel like I am sitting on an atomic bomb, waiting for it to go off.",
    "People are changing all the time.",
    "Hey everybody, let's go inside and eat some cake.",
    "Don't tuch me mother fucker!",
    "Whose baby is it, is it mine?",
    "You really don't know, do you?",
    "You my future wife.",
    "Wake up man, what planet are you on?",
    "Don't spoil it, we were just having fun.",
    "Don't touch me mother fucker!",
    "If you keep your girl satisfied, she wouldn't have come to me!",
    "You couldn't kill me if you tried.",
    "You just a chicken.",
    "You just a chicken. Chip chip chip chip chip.",
    "Everybody betray me. I fed up with this world!",
    "Everybody betray me.",
    "I fed up with this world!",
    "I cleaned up the kitchen sweatheart, so you don't have to worry about that.",
    "In a minute bitch.",
    "Who are you calling a bitch?",
    "You and your stupid mother.",
    "Don't worry about Johnny, he's just being a big babby.",
    "Why don't you ditch this creep, I don't like him anymore.",
    "Sure babby, come on up. I want your body.",
    "I record everything.",
    "You little tramp!",
    "I gave you seven years of my life!",
    "I put up with you for seven years!",
    "I treat you like a princess.",
    "God... forgive me.",
    "Everybody betray me. I don't have afriend in the world.",
    "Get out, get out, get out of my life!",
    "Why Lisa, why, why! Aaaaaaaghhhh",
    "Is he dead?",
    "Wake up Johnny, come on!",
    "You tramp.",
    "Why? Why is this happening to me? Why?",
    "You don't have me. You'll never have me!",
    "Mark, we're free to be together.",
    "Get out of my life, you bitch!",
    "Wake up Johnny!",
    "As far as I'm concerned, you can drop off the earth. It's a promise.",
    "Why Johnny, Johnny why?"
];

export default theRoomQuotes;